import type { RefObject } from "react";
import { LiveCaption, type LiveCaptionSize, type LiveCaptionStatus } from "@/components/LiveCaption";
import { LiveSummaryPanel } from "@/components/LiveSummaryPanel";
import { SequentialAvatarPlayer, type SequentialAvatarPlayerHandle } from "@/components/SequentialAvatarPlayer";
import type { LiveSummary, SignCard } from "@/types/live";

export function LiveCaptionRegion({ text, size, status, paused, onTogglePause }: { text: string; size: LiveCaptionSize; status: LiveCaptionStatus; paused: boolean; onTogglePause: () => void }) {
  return <LiveCaption text={text} size={size} status={status} paused={paused} onTogglePause={onTogglePause} />;
}

export function AvatarRegion({ items, playerRef, onPlaybackStateChange }: { items: SignCard[]; playerRef: RefObject<SequentialAvatarPlayerHandle | null>; onPlaybackStateChange: (paused: boolean) => void }) {
  return <div className="min-w-0 max-w-full overflow-hidden"><SequentialAvatarPlayer ref={playerRef} items={items} onPlaybackStateChange={onPlaybackStateChange} /></div>;
}

export function LiveSummaryRegion({ summary, textScale, onIncreaseText, onDecreaseText }: { summary: LiveSummary | null; textScale: 0 | 1 | 2; onIncreaseText: () => void; onDecreaseText: () => void }) {
  return <div className="min-w-0 max-w-full overflow-hidden"><LiveSummaryPanel summaryText={summary?.summaryText} bulletPoints={summary?.bulletPoints} keywords={summary?.keywords} updatedAt={summary?.updatedAt} generatedBy={summary?.generatedBy} isAutoGenerated={summary?.isAutoGenerated} textScale={textScale} onIncreaseText={onIncreaseText} onDecreaseText={onDecreaseText} collapsible defaultOpen /></div>;
}
