"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, Minus, Plus, Sparkles } from "lucide-react";

export function LiveSummaryPanel({
  summaryText,
  bulletPoints = [],
  keywords = [],
  updatedAt,
  generatedBy,
  isAutoGenerated = true,
  loading = false,
  enlarged = false,
  textScale,
  collapsible = true,
  defaultOpen = true,
  onIncreaseText,
  onDecreaseText,
}: {
  summaryText?: string;
  bulletPoints?: string[];
  keywords?: string[];
  updatedAt?: string;
  generatedBy?: string;
  isAutoGenerated?: boolean;
  loading?: boolean;
  enlarged?: boolean;
  textScale?: 0 | 1 | 2;
  collapsible?: boolean;
  defaultOpen?: boolean;
  onIncreaseText?: () => void;
  onDecreaseText?: () => void;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const hasSummary = Boolean(summaryText || bulletPoints.length || keywords.length);
  const originLabel = generatedBy === "ai" || generatedBy === "openai" || generatedBy === "openai_compatible" ? "IA" : "resumo local";
  const effectiveScale = textScale ?? (enlarged ? 1 : 0);
  const titleSize = effectiveScale === 2 ? "text-2xl" : effectiveScale === 1 ? "text-xl" : "text-lg";
  const descriptionSize = effectiveScale > 0 ? "text-sm" : "text-xs";
  const summarySize = effectiveScale === 2 ? "text-2xl" : effectiveScale === 1 ? "text-xl" : "text-base";
  const bulletSize = effectiveScale === 2 ? "text-xl" : effectiveScale === 1 ? "text-lg" : "text-sm";
  const keywordSize = effectiveScale > 0 ? "text-sm" : "text-xs";
  const metadataSize = effectiveScale > 0 ? "text-sm" : "text-xs";

  return (
    <section
      className="rounded-lg border border-ocean/20 bg-white p-4 shadow-soft dark:border-white/10 dark:bg-zinc-900"
      aria-live="polite"
    >
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h2 className={`${titleSize} font-black text-ink dark:text-white`}>Resumo da aula até agora</h2>
            {isAutoGenerated && (
              <span className={`inline-flex items-center gap-1 rounded-full bg-ocean/10 px-3 py-1 ${keywordSize} font-black text-ocean dark:bg-mint/10 dark:text-mint`}>
                <Sparkles className="h-4 w-4" aria-hidden="true" />
                gerado automaticamente
              </span>
            )}
          </div>
          <p className={`mt-1 ${descriptionSize} font-bold text-ink/60 dark:text-white/60`}>
            Resumo automático pode conter limitações. Use como apoio ao estudo.
          </p>
        </div>
        <div className="flex flex-wrap justify-end gap-2">
          {(onIncreaseText || onDecreaseText) && (
            <div className="inline-flex rounded-lg border border-ink/10 bg-teal-50 p-1 dark:border-white/10 dark:bg-zinc-800" aria-label="Tamanho do texto do resumo">
              <button type="button" className="focus-ring grid h-10 w-10 place-items-center rounded-md text-ocean disabled:opacity-40 dark:text-mint" onClick={onDecreaseText} disabled={!onDecreaseText || effectiveScale === 0} aria-label="Reduzir texto do resumo">
                <Minus className="h-4 w-4" aria-hidden="true" />
              </button>
              <button type="button" className="focus-ring grid h-10 w-10 place-items-center rounded-md text-ocean disabled:opacity-40 dark:text-mint" onClick={onIncreaseText} disabled={!onIncreaseText || effectiveScale === 2} aria-label="Aumentar texto do resumo">
                <Plus className="h-4 w-4" aria-hidden="true" />
              </button>
            </div>
          )}
          {collapsible && (
            <button
              className="focus-ring inline-flex min-h-11 items-center gap-1 rounded-lg bg-teal-50 px-3 py-2 text-sm font-bold text-ocean dark:bg-zinc-800 dark:text-mint"
              onClick={() => setOpen((value) => !value)}
              aria-expanded={open}
              aria-label={open ? "Ocultar resumo da aula" : "Mostrar resumo da aula"}
            >
              {open ? <ChevronUp className="h-4 w-4" aria-hidden="true" /> : <ChevronDown className="h-4 w-4" aria-hidden="true" />}
              {open ? "Ocultar" : "Mostrar"}
            </button>
          )}
        </div>
      </div>

      {open && (
        <div className="mt-4 space-y-3">
          {loading && <p className={`rounded-lg bg-teal-50 p-3 ${bulletSize} font-bold text-ink dark:bg-zinc-800 dark:text-white`}>Gerando resumo...</p>}
          {!hasSummary && !loading && (
            <p className={`rounded-lg bg-teal-50 p-3 ${bulletSize} font-bold leading-relaxed text-ink/75 dark:bg-zinc-800 dark:text-white/75`}>
              Assim que a aula avançar, um resumo automático aparecerá aqui.
            </p>
          )}
          {summaryText && <p className={`${summarySize} font-semibold leading-relaxed text-ink/80 dark:text-white/80`}>{summaryText}</p>}
          {bulletPoints.length > 0 && (
            <ul className="space-y-2">
              {bulletPoints.map((item, index) => (
                <li key={`${item}-${index}`} className={`rounded-lg bg-teal-50 p-3 ${bulletSize} font-bold leading-relaxed text-ink dark:bg-zinc-800 dark:text-white`}>
                  {item}
                </li>
              ))}
            </ul>
          )}
          {keywords.length > 0 && (
            <div className="flex flex-wrap gap-2" aria-label="Palavras-chave do resumo">
              {keywords.map((keyword, index) => (
                <span key={`${keyword}-${index}`} className={`rounded-full bg-amber/20 px-3 py-2 ${keywordSize} font-black text-ink dark:text-white`}>
                  {keyword}
                </span>
              ))}
            </div>
          )}
          {(updatedAt || generatedBy) && (
            <p className={`${metadataSize} font-bold text-ink/55 dark:text-white/55`}>
              {updatedAt ? `Última atualização: ${new Date(updatedAt).toLocaleString("pt-BR")}` : ""}
              {generatedBy ? ` • origem: ${originLabel}` : ""}
            </p>
          )}
        </div>
      )}
    </section>
  );
}
