"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, Sparkles } from "lucide-react";

export function LiveSummaryPanel({
  summaryText,
  bulletPoints = [],
  keywords = [],
  updatedAt,
  generatedBy,
  isAutoGenerated = true,
  loading = false,
  collapsible = true,
  defaultOpen = true,
}: {
  summaryText?: string;
  bulletPoints?: string[];
  keywords?: string[];
  updatedAt?: string;
  generatedBy?: string;
  isAutoGenerated?: boolean;
  loading?: boolean;
  collapsible?: boolean;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const hasSummary = Boolean(summaryText || bulletPoints.length || keywords.length);
  const originLabel = generatedBy === "ai" || generatedBy === "openai" || generatedBy === "openai_compatible" ? "IA" : "resumo local";

  return (
    <section
      className="rounded-lg border border-ocean/20 bg-white p-4 shadow-soft dark:border-white/10 dark:bg-zinc-900"
      aria-live="polite"
    >
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h2 className="text-lg font-black text-ink dark:text-white">Resumo da aula até agora</h2>
            {isAutoGenerated && (
              <span className="inline-flex items-center gap-1 rounded-full bg-ocean/10 px-3 py-1 text-xs font-black text-ocean dark:bg-mint/10 dark:text-mint">
                <Sparkles className="h-4 w-4" aria-hidden="true" />
                gerado automaticamente
              </span>
            )}
          </div>
          <p className="mt-1 text-xs font-bold text-ink/60 dark:text-white/60">
            Resumo automático pode conter limitações. Use como apoio ao estudo.
          </p>
        </div>
        {collapsible && (
          <button
            className="focus-ring inline-flex min-h-10 items-center gap-1 rounded-lg bg-teal-50 px-3 py-2 text-sm font-bold text-ocean dark:bg-zinc-800 dark:text-mint"
            onClick={() => setOpen((value) => !value)}
            aria-expanded={open}
            aria-label={open ? "Ocultar resumo da aula" : "Mostrar resumo da aula"}
          >
            {open ? <ChevronUp className="h-4 w-4" aria-hidden="true" /> : <ChevronDown className="h-4 w-4" aria-hidden="true" />}
            {open ? "Ocultar resumo" : "Mostrar resumo"}
          </button>
        )}
      </div>

      {open && (
        <div className="mt-4 space-y-3">
          {loading && <p className="rounded-lg bg-teal-50 p-3 text-sm font-bold text-ink dark:bg-zinc-800 dark:text-white">Gerando resumo...</p>}
          {!hasSummary && !loading && (
            <p className="rounded-lg bg-teal-50 p-3 text-sm font-bold leading-relaxed text-ink/75 dark:bg-zinc-800 dark:text-white/75">
              Assim que a aula avançar, um resumo automático aparecerá aqui.
            </p>
          )}
          {summaryText && <p className="text-base font-semibold leading-relaxed text-ink/80 dark:text-white/80">{summaryText}</p>}
          {bulletPoints.length > 0 && (
            <ul className="space-y-2">
              {bulletPoints.map((item, index) => (
                <li key={`${item}-${index}`} className="rounded-lg bg-teal-50 p-3 text-sm font-bold leading-relaxed text-ink dark:bg-zinc-800 dark:text-white">
                  {item}
                </li>
              ))}
            </ul>
          )}
          {keywords.length > 0 && (
            <div className="flex flex-wrap gap-2" aria-label="Palavras-chave do resumo">
              {keywords.map((keyword, index) => (
                <span key={`${keyword}-${index}`} className="rounded-full bg-amber/20 px-3 py-2 text-xs font-black text-ink dark:text-white">
                  {keyword}
                </span>
              ))}
            </div>
          )}
          {(updatedAt || generatedBy) && (
            <p className="text-xs font-bold text-ink/55 dark:text-white/55">
              {updatedAt ? `Última atualização: ${new Date(updatedAt).toLocaleString("pt-BR")}` : ""}
              {generatedBy ? ` • origem: ${originLabel}` : ""}
            </p>
          )}
        </div>
      )}
    </section>
  );
}
