import type { AdminStats, AuthResponse, AuthUser, ClassReview, ClassSession, LiveSummary, SignCategory, SignRecord, Subject } from "@/types/live";

export function normalizeApiBase(value?: string) {
  const normalized = (value?.trim() || "http://localhost:8000").replace(/\/+$/, "");
  return normalized.replace(/(?:\/api)+$/i, "");
}

export const API_BASE = normalizeApiBase(process.env.NEXT_PUBLIC_API_URL);
export const WS_BASE = API_BASE.replace(/^http/, "ws");

export function getStoredAccessToken() {
  if (typeof window === "undefined") return null;
  return window.sessionStorage.getItem("libraslive.access_token");
}

export function getStoredRefreshToken() {
  if (typeof window === "undefined") return null;
  return window.sessionStorage.getItem("libraslive.refresh_token");
}

export function storeAuthTokens(response: AuthResponse) {
  if (typeof window === "undefined") return;
  window.sessionStorage.setItem("libraslive.access_token", response.access_token);
  window.sessionStorage.setItem("libraslive.refresh_token", response.refresh_token);
  window.sessionStorage.setItem("libraslive.user", JSON.stringify(response.user));
}

export function clearAuthTokens() {
  if (typeof window === "undefined") return;
  window.sessionStorage.removeItem("libraslive.access_token");
  window.sessionStorage.removeItem("libraslive.refresh_token");
  window.sessionStorage.removeItem("libraslive.user");
  navigator.serviceWorker?.controller?.postMessage({ type: "CLEAR_PRIVATE_CACHE" });
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const token = getStoredAccessToken();
  const response = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(init?.headers ?? {}),
    },
  });
  if (!response.ok) {
    throw new Error(`API ${response.status}: ${await response.text()}`);
  }
  return response.json() as Promise<T>;
}

export function listSubjects(): Promise<Subject[]> {
  return request<Subject[]>("/api/subjects");
}

export function listCategories(): Promise<SignCategory[]> {
  return request<SignCategory[]>("/api/categories");
}

export function createClass(payload: {
  title: string;
  subject_id?: number | null;
  max_participants?: number;
  allow_anonymous_students?: boolean;
  require_teacher_approval?: boolean;
}): Promise<ClassSession> {
  return request<ClassSession>("/api/classes", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function getClassByAccessCode(accessCode: string): Promise<ClassSession> {
  return request<ClassSession>(`/api/classes/access/${encodeURIComponent(accessCode)}`);
}

export function joinClass(accessCode: string, token?: string | null): Promise<ClassSession> {
  const query = token ? `?token=${encodeURIComponent(token)}` : "";
  return request<ClassSession>(`/api/classes/access/${encodeURIComponent(accessCode)}/join${query}`, { method: "POST" });
}

export function sendDemoTick(classSessionId: number, step: number) {
  return request<{ line: string; events: Array<{ event: string; payload: Record<string, unknown> }> }>(
    `/api/classes/${classSessionId}/demo-tick?step=${step}`,
    { method: "POST" }
  );
}

export function sendTranscript(classSessionId: number, text: string, confidence = 0.96) {
  return request<Array<{ event: string; payload: Record<string, unknown> }>>(`/api/classes/${classSessionId}/transcript`, {
    method: "POST",
    body: JSON.stringify({ text, confidence }),
  });
}

export function pauseClass(classSessionId: number) {
  return request<{ status: string }>(`/api/classes/${classSessionId}/pause`, { method: "POST" });
}

export function finishClass(classSessionId: number) {
  return request<{ status: string; summary: string; keywords: string[] }>(`/api/classes/${classSessionId}/finish`, {
    method: "POST",
  });
}

export function createSummary(classSessionId: number) {
  return request<{ id: number; summary: string; keywords: string[] }>(`/api/classes/${classSessionId}/summary`, {
    method: "POST",
  });
}

export function createLiveSummary(classSessionId: number) {
  return request<{
    summary_text?: string;
    summaryText?: string;
    bullet_points?: string[];
    bulletPoints?: string[];
    keywords?: string[];
    generated_by?: string;
    generatedBy?: string;
    is_auto_generated?: boolean;
    isAutoGenerated?: boolean;
    updated_at?: string;
    updatedAt?: string;
  }>(`/api/classes/${classSessionId}/summary/live`, { method: "POST" }).then(mapLiveSummary);
}

export function getLiveSummaryByAccessCode(accessCode: string) {
  return request<{
    summary_text?: string;
    summaryText?: string;
    bullet_points?: string[];
    bulletPoints?: string[];
    keywords?: string[];
    generated_by?: string;
    generatedBy?: string;
    is_auto_generated?: boolean;
    isAutoGenerated?: boolean;
    updated_at?: string;
    updatedAt?: string;
  }>(`/api/classes/access/${encodeURIComponent(accessCode)}/summary/live`).then(mapLiveSummary);
}

export const getLiveSummary = getLiveSummaryByAccessCode;

export function mapLiveSummary(payload: {
  summary_text?: string;
  summaryText?: string;
  bullet_points?: string[];
  bulletPoints?: string[];
  keywords?: string[];
  generated_by?: string;
  generatedBy?: string;
  is_auto_generated?: boolean;
  isAutoGenerated?: boolean;
  updated_at?: string;
  updatedAt?: string;
}): LiveSummary {
  return {
    summaryText: payload.summaryText ?? payload.summary_text ?? "",
    bulletPoints: payload.bulletPoints ?? payload.bullet_points ?? [],
    keywords: payload.keywords ?? [],
    generatedBy: payload.generatedBy ?? payload.generated_by,
    isAutoGenerated: payload.isAutoGenerated ?? payload.is_auto_generated,
    updatedAt: payload.updatedAt ?? payload.updated_at,
  };
}

export function getReviewByAccessCode(accessCode: string): Promise<ClassReview> {
  return request<ClassReview>(`/api/classes/access/${encodeURIComponent(accessCode)}/review`);
}

export function saveWord(payload: {
  sign_id?: number;
  word?: string;
  access_code?: string;
  class_session_id?: number;
  notes?: string;
}) {
  return request<{ id: number; word: string; status: string }>("/api/saved-words", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function getAdminStats(): Promise<AdminStats> {
  return request<AdminStats>("/api/admin/stats");
}

export function listSigns(params: URLSearchParams): Promise<SignRecord[]> {
  const query = params.toString();
  return request<SignRecord[]>(`/api/signs${query ? `?${query}` : ""}`);
}

export function approveSign(signId: number): Promise<SignRecord> {
  return request<SignRecord>(`/api/signs/${signId}/approve`, { method: "POST" });
}

export function rejectSign(signId: number, reason: string): Promise<SignRecord> {
  return request<SignRecord>(`/api/signs/${signId}/reject`, {
    method: "POST",
    body: JSON.stringify({ reason }),
  });
}

export function listSignAudit(signId: number) {
  return request<Array<{ id: number; action: string; created_at: string; old_value?: unknown; new_value?: unknown }>>(
    `/api/signs/${signId}/audit`
  );
}

export function updateSign(signId: number, payload: Partial<SignRecord>): Promise<SignRecord> {
  return request<SignRecord>(`/api/signs/${signId}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export type SignMediaPayload = {
  gloss?: string | null;
  source_name?: string | null;
  source_url?: string | null;
  source_reference_url?: string | null;
  license?: string | null;
  license_notes?: string | null;
  video_url?: string | null;
  avatar_video_url?: string | null;
  avatar_gif_url?: string | null;
  avatar_animation_url?: string | null;
  image_url?: string | null;
  curator_notes?: string | null;
};

export function updateSignMedia(signId: number, payload: SignMediaPayload): Promise<SignRecord> {
  return request<SignRecord>(`/api/signs/${signId}/media`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export type ManualSignPayload = {
  word: string;
  gloss?: string;
  example_sentence?: string;
  grammatical_class?: string;
  meaning?: string;
  handshape?: string;
  movement?: string;
  location?: string;
  orientation?: string;
  facial_expression?: string;
  source_name?: string;
  source_url?: string;
  source_reference_url?: string;
  license?: string;
  license_notes?: string;
  image_url?: string;
  video_url?: string;
  avatar_video_url?: string;
  avatar_gif_url?: string;
  animation_payload_url?: string;
  curator_notes?: string;
};

export function createManualSign(payload: ManualSignPayload): Promise<SignRecord> {
  return request<SignRecord>("/api/signs/manual", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function curateSign(signId: number, payload: { status: string; curator_notes?: string }): Promise<SignRecord> {
  return request<SignRecord>(`/api/signs/${signId}/curation`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export function lookupSign(word: string) {
  return request(`/api/signs/lookup?word=${encodeURIComponent(word)}`);
}

export function importSampleJson() {
  return request("/api/admin/import", {
    method: "POST",
    body: JSON.stringify({
      source_type: "json",
      source: "data/sample_libras_dictionary.json",
    }),
  });
}

export function importSampleCsv() {
  return request("/api/admin/import", {
    method: "POST",
    body: JSON.stringify({
      source_type: "csv",
      source: "data/sample_libras_dictionary.csv",
    }),
  });
}

export function importViaApi(providerName = "vlibras") {
  return request("/api/admin/import", {
    method: "POST",
    body: JSON.stringify({
      source_type: "api",
      source: providerName,
      provider_name: providerName,
    }),
  });
}

export function importInesAuthorizedMedia(payload: {
  source?: string;
  source_type?: "csv" | "json";
  content?: string;
  records?: Array<Record<string, string>>;
  download_media?: boolean;
  overwrite_files?: boolean;
  authorized?: boolean;
  authorization_reference?: string;
}) {
  return request("/api/admin/import/ines-media", {
    method: "POST",
    body: JSON.stringify({
      source_type: "json",
      download_media: false,
      overwrite_files: false,
      authorized: false,
      ...payload,
    }),
  });
}

export type InesImportMode = "pending_words" | "selected_words" | "json_items" | "csv_items";

export type InesImportItem = {
  word?: string;
  gloss?: string;
  source_name?: string;
  source_url?: string;
  source_reference_url?: string;
  video_url?: string;
  avatar_video_url?: string;
  avatar_gif_url?: string;
  gif_url?: string;
  image_url?: string;
  license?: string;
  license_notes?: string;
  curator_notes?: string;
  authorized?: boolean;
  example_sentence?: string;
  grammatical_class?: string;
  meaning?: string;
};

export type InesImportStartPayload = {
  mode: InesImportMode;
  words?: string[];
  items?: InesImportItem[];
  csv?: string;
  max_items?: number;
  approve_authorized?: boolean;
  download_media?: boolean;
  store_remote_url?: boolean;
  overwrite?: boolean;
};

export type InesImportReport = {
  total_items: number;
  processed_items: number;
  created_count: number;
  updated_count: number;
  approved_count: number;
  pending_count: number;
  skipped_count: number;
  error_count: number;
  video_found_count?: number;
  gif_found_count?: number;
  image_found_count?: number;
  video_missing_count?: number;
  errors: Array<{ word?: string | null; message: string }>;
  warnings?: Array<{ word?: string | null; message: string }>;
  items?: Array<{
    word: string;
    page_loaded?: boolean;
    word_found?: boolean;
    video_found?: boolean;
    gif_found?: boolean;
    image_found?: boolean;
    media_type?: string;
    detection_method?: string;
    can_use_avatar?: boolean;
    video_url?: string | null;
    gif_url?: string | null;
    avatar_gif_url?: string | null;
    source_reference_url?: string | null;
    image_url?: string | null;
    status?: string;
    reason?: string;
    recommended_action?: string;
    warnings?: string[];
    errors?: string[];
  }>;
  manual_required?: Array<{ word?: string | null; source_reference_url?: string | null; reason: string }>;
};

export type InesImportJobResponse = {
  job_id?: number | null;
  status: string;
  report: InesImportReport;
};

export type InesDiagnoseResult = {
  word: string;
  normalized_word: string;
  search_url: string;
  http_status?: number | null;
  page_loaded: boolean;
  word_found_in_page: boolean;
  source_reference_url?: string | null;
  image_found: boolean;
  image_url?: string | null;
  video_found: boolean;
  video_url?: string | null;
  gif_found?: boolean;
  gif_url?: string | null;
  media_type?: string;
  detection_method?: string;
  video_host_allowed: boolean;
  can_import: boolean;
  can_use_avatar?: boolean;
  reason: string;
  warnings: string[];
  errors: string[];
};

export type InesDiagnoseResponse = {
  status: string;
  total_items: number;
  results: InesDiagnoseResult[];
};

export function validateInesMediaImport(payload: InesImportStartPayload): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/ines-media/validate", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function startInesMediaImport(payload: InesImportStartPayload): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/ines-media/start", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function getInesMediaImportJob(jobId: number): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>(`/api/admin/import/ines-media/${jobId}`);
}

export function autoImportPendingInesMedia(payload: {
  max_items?: number;
  approve_authorized?: boolean;
  overwrite?: boolean;
}): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/ines-media/auto-pending", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function autoImportSelectedInesMedia(payload: {
  words: string[];
  max_items?: number;
  approve_authorized?: boolean;
  overwrite?: boolean;
}): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/ines-media/auto-selected", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function diagnoseInesMediaImport(payload: { words: string[]; max_items?: number }): Promise<InesDiagnoseResponse> {
  return request<InesDiagnoseResponse>("/api/admin/import/ines-media/diagnose", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export type MediaAutoFillSource = "ines" | "ifpr";

export type MediaAutoFillReportItem = {
  word: string;
  normalized_word?: string;
  source_used?: string | null;
  media_type?: string;
  detection_method?: string;
  media_found?: boolean;
  video_found?: boolean;
  gif_found?: boolean;
  image_found?: boolean;
  can_use_avatar?: boolean;
  validated?: boolean | null;
  http_status?: number | null;
  content_type?: string | null;
  validation_status_code?: number | null;
  validation_content_type?: string | null;
  validation_final_url?: string | null;
  validation_content_length?: number | null;
  validation_reason?: string | null;
  video_url?: string | null;
  avatar_gif_url?: string | null;
  avatar_animation_url?: string | null;
  image_url?: string | null;
  source_reference_url?: string | null;
  status?: string;
  reason?: string;
  recommended_action?: string;
  warnings?: string[];
  errors?: string[];
};

export type MediaValidationExpectedType = "video" | "gif" | "animation";

export type MediaValidationResult = {
  valid: boolean;
  url: string;
  final_url?: string | null;
  status_code?: number | null;
  content_type?: string | null;
  content_length?: number | null;
  media_type: string;
  reason: string;
};

export function validateMediaUrl(payload: {
  url: string;
  expected_type: MediaValidationExpectedType;
}): Promise<MediaValidationResult> {
  return request<MediaValidationResult>("/api/admin/media/validate-url", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export type MediaAutoFillReport = {
  status: string;
  total_items: number;
  processed_items: number;
  media_found_count: number;
  video_found_count: number;
  gif_found_count: number;
  image_found_count: number;
  media_missing_count: number;
  created_count: number;
  updated_count: number;
  pending_count: number;
  skipped_count: number;
  error_count: number;
  items: MediaAutoFillReportItem[];
  warnings: Array<{ word?: string | null; message: string }>;
  errors: Array<{ word?: string | null; message: string }>;
};

export type MediaAutoFillResponse = {
  job_id?: number | null;
  status: string;
  report: MediaAutoFillReport;
};

export type InesStandardVideoReportItem = {
  word: string;
  normalized_word?: string;
  generated_url: string;
  video_url?: string | null;
  avatar_video_url?: string | null;
  validated?: boolean;
  http_status?: number | null;
  content_type?: string | null;
  validation_final_url?: string | null;
  validation_content_length?: number | null;
  validation_reason?: string | null;
  can_use_avatar?: boolean;
  detection_method?: string;
  status?: string;
  reason?: string;
  recommended_action?: string;
  warnings?: string[];
  errors?: string[];
};

export type InesStandardVideoReport = {
  status: string;
  total_items: number;
  processed_items: number;
  valid_videos: number;
  invalid_videos: number;
  updated_count: number;
  created_count?: number;
  pending_count?: number;
  skipped_count: number;
  error_count: number;
  items: InesStandardVideoReportItem[];
  warnings: Array<{ word?: string | null; message: string }>;
  errors: Array<{ word?: string | null; message: string }>;
};

export type InesStandardVideoResponse = {
  job_id?: number | null;
  status: string;
  report: InesStandardVideoReport;
};

export function diagnoseInesStandardVideo(payload: {
  words: string[];
  max_items?: number;
}): Promise<InesStandardVideoResponse> {
  return request<InesStandardVideoResponse>("/api/admin/ines-standard-video/diagnose", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function fillSelectedInesStandardVideo(payload: {
  words: string[];
  max_items?: number;
  overwrite?: boolean;
}): Promise<InesStandardVideoResponse> {
  return request<InesStandardVideoResponse>("/api/admin/ines-standard-video/fill-selected", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function fillPendingInesStandardVideo(payload: {
  max_items?: number;
  overwrite?: boolean;
}): Promise<InesStandardVideoResponse> {
  return request<InesStandardVideoResponse>("/api/admin/ines-standard-video/fill-pending", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export type CrawlReport = {
  status: string;
  source: string;
  pages_visited?: number;
  entries_found?: number;
  videos_found?: number;
  support_images_found?: number;
  entries_without_video?: number;
  gifs_found?: number;
  errors_count?: number;
  duplicates_count?: number;
  manifest_path?: string | null;
  pages_without_gif?: number;
};

export type CrawlResponse = {
  job_id?: number | null;
  status: string;
  report: CrawlReport;
  manifest?: Record<string, unknown> | null;
};

export type InesCatalogReportItem = {
  word?: string | null;
  letter?: string | null;
  media_type?: string | null;
  video_url?: string | null;
  avatar_video_url?: string | null;
  image_url?: string | null;
  handshape_image_url?: string | null;
  http_status?: number | null;
  content_type?: string | null;
  can_use_avatar?: boolean;
  validated?: boolean;
  image_validated?: boolean;
  status?: string | null;
  detection_method?: string | null;
  reason?: string | null;
  recommended_action?: string | null;
};

export type InesCatalogReport = {
  status: string;
  source?: string;
  letters_scanned?: number;
  entries_found?: number;
  videos_found?: number;
  images_found?: number;
  without_video?: number;
  imported_count?: number;
  skipped_count?: number;
  errors_count?: number;
  total_items?: number;
  processed_items?: number;
  created_count?: number;
  updated_count?: number;
  pending_count?: number;
  error_count?: number;
  video_found_count?: number;
  image_found_count?: number;
  video_missing_count?: number;
  manifest_path?: string | null;
  items?: InesCatalogReportItem[];
  warnings?: Array<{ word?: string | null; message: string }>;
  errors?: Array<{ word?: string | null; message: string }>;
};

export type InesCatalogResponse = {
  job_id?: number | null;
  status: string;
  report: InesCatalogReport;
  manifest?: Record<string, unknown> | null;
};

export function scanInesCatalog(payload: {
  letters?: string[];
  max_items?: number;
  delay_ms?: number;
  dry_run?: boolean;
  use_browser?: boolean;
  overwrite_manifest?: boolean;
}): Promise<InesCatalogResponse> {
  return request<InesCatalogResponse>("/api/admin/ines-catalog/scan", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function validateInesCatalogManifest(payload: {
  manifest_path?: string;
  manifest?: Record<string, unknown>;
  max_items?: number;
}): Promise<InesCatalogResponse> {
  return request<InesCatalogResponse>("/api/admin/ines-catalog/validate-manifest", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function importInesCatalog(payload: {
  manifest_path?: string;
  manifest?: Record<string, unknown>;
  overwrite?: boolean;
  max_items?: number;
  status?: "pending" | "review" | "needs_specialist_review";
}): Promise<InesCatalogResponse> {
  return request<InesCatalogResponse>("/api/admin/ines-catalog/import", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function startInesCrawler(payload: {
  max_pages?: number;
  delay_ms?: number;
  output?: string;
  dry_run?: boolean;
  words?: string[];
}): Promise<CrawlResponse> {
  return request<CrawlResponse>("/api/admin/crawl/ines-media/start", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function startLibrasGifCrawler(payload: {
  max_pages?: number;
  delay_ms?: number;
  output?: string;
  dry_run?: boolean;
}): Promise<CrawlResponse> {
  return request<CrawlResponse>("/api/admin/crawl/libras-gifs/start", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function importMediaManifest(payload: {
  source: "ines" | "ifpr" | "combined";
  manifest: Record<string, unknown>;
  approve_authorized?: boolean;
  overwrite?: boolean;
}): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/media-manifest", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function diagnoseMediaAutoFill(payload: {
  words: string[];
  max_items?: number;
  source_priority?: MediaAutoFillSource[];
}): Promise<MediaAutoFillResponse> {
  return request<MediaAutoFillResponse>("/api/admin/media-auto-fill/diagnose", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function startMediaAutoFillPending(payload: {
  max_items?: number;
  source_priority?: MediaAutoFillSource[];
  overwrite?: boolean;
}): Promise<MediaAutoFillResponse> {
  return request<MediaAutoFillResponse>("/api/admin/media-auto-fill/pending", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function startMediaAutoFillSelected(payload: {
  words: string[];
  max_items?: number;
  source_priority?: MediaAutoFillSource[];
  overwrite?: boolean;
}): Promise<MediaAutoFillResponse> {
  return request<MediaAutoFillResponse>("/api/admin/media-auto-fill/selected", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export type LibrasGifMediaItem = {
  word: string;
  gloss?: string;
  avatar_gif_url?: string;
  gif_url?: string;
  image_url?: string;
  source_name?: string;
  source_url?: string;
  source_reference_url?: string;
  license?: string;
  license_notes?: string;
  curator_notes?: string;
  authorized?: boolean;
};

export function importLibrasGifMedia(payload: {
  source_name?: string;
  source_url?: string;
  items: LibrasGifMediaItem[];
  approve_authorized?: boolean;
  overwrite?: boolean;
}): Promise<InesImportJobResponse> {
  return request<InesImportJobResponse>("/api/admin/import/libras-gif-media", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function login(payload: { email: string; password: string }): Promise<AuthResponse> {
  return request<AuthResponse>("/api/auth/login", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function register(payload: {
  name: string;
  email: string;
  password: string;
  role: string;
  guardian_email?: string;
  school_name?: string;
  birth_date?: string;
  accept_terms?: boolean;
  accept_privacy?: boolean;
}): Promise<AuthResponse> {
  return request<AuthResponse>("/api/auth/register", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function getMe(): Promise<AuthUser> {
  return request<AuthUser>("/api/auth/me");
}

export function logoutRequest() {
  return request<{ status: string }>("/api/auth/logout", { method: "POST" });
}

export function submitConsent(payload: {
  guardian_name?: string;
  guardian_email?: string;
  consent_type?: string;
  consent_text_version?: string;
}) {
  return request("/api/consent", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function getPrivacyPolicy() {
  return request<{ notice: string; retention: unknown[] }>("/api/privacy/policy");
}

export function deleteMyData() {
  return request<{ status: string }>("/api/me/data", { method: "DELETE" });
}
