import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const createClass = vi.fn(() =>
  Promise.resolve({
    id: 7,
    title: "Aula de tecnologia",
    subject_id: 1,
    access_code: "AULA-8F4K-29QX",
    status: "active",
  })
);

vi.mock("@/features/auth/AuthProvider", () => ({
  useRequireRole: () => ({
    loading: false,
    user: { id: 1, name: "Professora Ana", email: "ana@example.com", role: "professor" },
  }),
  useAuth: () => ({
    loading: false,
    isAuthenticated: true,
    user: { id: 1, name: "Professora Ana", email: "ana@example.com", role: "professor" },
  }),
}));

vi.mock("@/components/QrCode", () => ({
  QrCode: ({ code }: { code: string }) => <div>QR Code para {code}</div>,
}));

vi.mock("@/services/speech", () => ({
  createBrowserSpeechRecognition: () => null,
}));

vi.mock("@/services/api", () => ({
  createClass,
  createLiveSummary: vi.fn(() =>
    Promise.resolve({
      summaryText: "Resumo da aula.",
      bulletPoints: [],
      keywords: ["tecnologia", "sistema"],
      generatedBy: "local_fallback",
      isAutoGenerated: true,
      updatedAt: new Date().toISOString(),
    })
  ),
  createSummary: vi.fn(() => Promise.resolve({ summary: "Resumo da aula." })),
  finishClass: vi.fn(() => Promise.resolve({ summary: "Resumo final.", keywords: ["tecnologia"], status: "finished" })),
  listSubjects: vi.fn(() => Promise.resolve([{ id: 1, name: "Tecnologia" }])),
  pauseClass: vi.fn(() => Promise.resolve({ status: "paused" })),
  sendDemoTick: vi.fn(),
  sendTranscript: vi.fn(() => Promise.resolve({})),
}));

describe("teacher classroom workflow", () => {
  beforeEach(() => {
    createClass.mockClear();
  });

  it("shows classroom control, realtime monitoring and after-class report sections", async () => {
    const { default: TeacherPage } = await import("@/app/teacher/page");
    render(<TeacherPage />);

    expect(screen.getByText(/controle da aula/i)).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /acompanhamento em tempo real/i })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /depois da aula/i })).toBeInTheDocument();
    expect(screen.getAllByRole("button", { name: /gerar relatório da aula/i }).length).toBeGreaterThan(0);
  });

  it("creates a class and generates a simple lesson report", async () => {
    const { default: TeacherPage } = await import("@/app/teacher/page");
    render(<TeacherPage />);

    fireEvent.change(screen.getByLabelText(/título da aula/i), { target: { value: "Aula de tecnologia" } });
    fireEvent.click(screen.getByRole("button", { name: /criar nova aula/i }));

    await waitFor(() => expect(createClass).toHaveBeenCalled());
    await screen.findByText(/aula criada com sucesso/i);
    fireEvent.click(screen.getAllByRole("button", { name: /gerar relatório da aula/i })[0]);

    expect(await screen.findByText(/relatório pronto para download/i)).toBeInTheDocument();
  });
});
